name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - '**' # Memicu workflow di branch mana pun saat kamu melakukan push

  workflow_dispatch: # Memungkinkan kamu menjalankan workflow secara manual jika dibutuhkan

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Daftarkan remote Hugging Face Space Wadidaw
          git remote add space https://kieldinata:$HF_TOKEN@huggingface.co/spaces/kieldinata/Wadidaw
          
          # 2. Buat branch lokal sementara agar tidak memicu error proteksi penghapusan branch di HF
          git checkout -b hf-sync-branch
          
          # 3. Push ke Hugging Face dengan opsi meloloskan gambar logo Wadidaw (.png)
          git push space hf-sync-branch:main --force --push-option=nobinary
