name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # <--- WAJIB TRUE agar GitHub Actions ikut mengunduh file biner LFS-mu

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://kieldinata:$HF_TOKEN@huggingface.co/spaces/kieldinata/Wadidaw
          git checkout -b hf-sync-branch
          # Push normal tanpa opsi aneh-aneh
          git push space hf-sync-branch:main --force
